version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meuusuario -d meubanco"]
      interval: 10s
      timeout: 5s
      retries: 5

  scraper:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://meuusuario:minhasenha@postgres:5432/meubanco

volumes:
  postgres_data: